// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Acme.BookStore.Authors;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Acme.BookStore.Authors;

public class CreateAuthorDto
{
    public string Name { get; set; }

    public DateTime BirthDate { get; set; }

    public string ShortBio { get; set; }
}
