// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Kompozit.Mdb.Materials.Documents;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Kompozit.Mdb.Materials.Documents;

public class GetСontentFileDto : EntityDto<Guid>
{
    public IRemoteStreamContent File { get; set; }
}
