// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Kompozit.Mdb.Letters;
using Kompozit.Mdb.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Kompozit.Mdb.Letters;

public interface ILetterAppService : IApplicationService
{
    Task<LetterDto> RegisterAsync(Guid id);

    Task<LetterDto> GetAsync(Guid id);

    Task<PagedResultDto<LetterDto>> GetListAsync(PagedAndSortedAndFilteredResultRequestDto input);

    Task<LetterDto> CreateAsync(CreateLetterDto input);

    Task<LetterDto> UpdateAsync(Guid id, UpdateLetterDto input);

    Task DeleteAsync(Guid id);
}
