// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Acme.BookStore.Books;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Acme.BookStore.Books;

public enum BookType
{
    Undefined = 0,
    Adventure = 1,
    Biography = 2,
    Dystopia = 3,
    Fantastic = 4,
    Horror = 5,
    Science = 6,
    ScienceFiction = 7,
    Poetry = 8
}
