// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Acme.BookStore.Books;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Acme.BookStore.Books;

public interface IBookAppService : IApplicationService
{
    Task<ListResultDto<AuthorLookupDto>> GetAuthorLookupAsync();

    Task<BookDto> GetAsync(Guid id);

    Task<PagedResultDto<BookDto>> GetListAsync(PagedAndSortedResultRequestDto input);

    Task<BookDto> CreateAsync(CreateUpdateBookDto input);

    Task<BookDto> UpdateAsync(Guid id, CreateUpdateBookDto input);

    Task DeleteAsync(Guid id);
}
