// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Kompozit.Mdb.Materials;
using Kompozit.Mdb.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Kompozit.Mdb.Materials;

public interface IMaterialAppService : IApplicationService
{
    Task<AnnotationDto> GetAnnotationAsync(Guid id);

    Task<MaterialDto> GetAsync(Guid id);

    Task<PagedResultDto<MaterialDto>> GetListAsync(PagedAndSortedAndFilteredResultRequestDto input);
}
