// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Kompozit.Mdb.Materials;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Kompozit.Mdb.Materials;

public class MaterialDto : EntityDto<Guid>
{
    public string Name { get; set; }

    public string Provider { get; set; }

    public DateTime? AdmissionDate { get; set; }

    public string[] ProviderNumbers { get; set; }

    public string InternalNumber { get; set; }

    public bool IsPublished { get; set; }

    public bool IsRegistered { get; set; }

    public AnnotationDto Annotation { get; set; }
}
