// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Kompozit.Mdb.Materials;
using Kompozit.Mdb.Shared;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Kompozit.Mdb.Materials;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMaterialAppService), typeof(MaterialClientProxy))]
public partial class MaterialClientProxy : ClientProxyBase<IMaterialAppService>, IMaterialAppService
{
    public virtual async Task<AnnotationDto> GetAnnotationAsync(Guid id)
    {
        return await RequestAsync<AnnotationDto>(nameof(GetAnnotationAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<MaterialDto> GetAsync(Guid id)
    {
        return await RequestAsync<MaterialDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<MaterialDto>> GetListAsync(PagedAndSortedAndFilteredResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<MaterialDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedAndSortedAndFilteredResultRequestDto), input }
        });
    }
}
